-- AlterEnum: add FOLLOWED_USER_MARKET and FOLLOWED_USER_OPINION to NotificationType (S24-T3)
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'FOLLOWED_USER_MARKET';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'FOLLOWED_USER_OPINION';
